config/routes.rb
Rails.application.routes.draw do
  root 'cohorts#index'
  resources :cohorts, :only => [] do
    resources :students
    get 'twitter/follow' => 'twitter#follow', :as => 'twitter_follow'
  end

  get '/cohorts' => 'cohorts#index', :as => 'cohorts'
  get '/cohorts/:id' => 'cohorts#show', :as => 'cohort'

  get '/signin' => 'sessions#new', :as => 'signin'
  get '/auth/twitter/callback' => 'sessions#create'
  delete '/signout' =>'sessions#destroy', :as => 'signout'

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  has_many :students

  validates :name, {:presence => true, :uniqueness => true}

  def student_twitter_handles(user)
    self.students.collect(&:twitter_handle).tap do |handles|
      handles.compact!.delete(user.username)
    end
  end
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_many :user_friends
  has_many :users, through: :user_friends

  validates_uniqueness_of :username, :scope => :provider

  def self.find_user_friends(user)
    self.joins(:users)
    .where(:provider => user.provider, users: {:id => user.id})
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :cohort

  def twitter_handle
    username(:twitter)
  end

  def github_handle
    username(:github)
  end

  private
  # works for RESTful URLs such as http://www.twitter.com/boredelonmusk
  def username(service)
    send(service).to_s[/\w+$/] || ""
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_friends
  has_many :friends, through: :user_friends

  validates :provider, :uid, {:presence => true}
  validates_uniqueness_of :uid, :scope => :provider

  def add_friends(usernames)
    usernames.each do |username|
      self.friends.create(:provider => self.provider, :username => username)
    end
  end

  def self.find_or_create_from_auth_hash(auth)
    User.find_by(:provider => auth["provider"], :uid => auth["uid"]) || User.create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
      user.username = auth["info"]["nickname"]
      user.img_url = TwitterFollower.new(user).get_image_url
    end
  end
end

app/models/user_friend.rb
class UserFriend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorized?
  before_action :authorize


  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to signin_path unless logged_in?
  end

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all.order(:name)
  end

  def show
    @cohort = Cohort.find(params[:id])
    @students = @cohort.students.order(:full_name)
    @friends = Friend.find_user_friends(current_user).collect(&:username)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorize, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    login(@user)
    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Signed out!'
    redirect_to signin_path
  end

  private
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, :only => [:show, :edit, :update, :destroy]
  before_action :set_cohort

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.cohort = @cohort
    if @student.save
      redirect_to cohort_student_path(@cohort, @student)
    else
      render 'students/new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @student.update(student_params)
    redirect_to cohort_student_path(@cohort, @student)
  end

  def destroy
    @student.destroy
    redirect_to cohort_path(@cohort)
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def set_cohort
      @cohort = Cohort.find(params[:cohort_id])
    end

    def student_params
      params.require(:student).permit(:full_name, :twitter, :linkedin, :github, :quote, :bio, :work_title, :education, :profile_image)
    end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

  def follow
    @cohort = Cohort.find(params[:cohort_id])
    @friends = @cohort.student_twitter_handles(current_user)
    current_user.add_friends(@friends)
    @followed = TwitterFollower.new(current_user).follow_users(@friends)
    flash[:new_friends] = @followed.collect(&:screen_name) if @followed
    redirect_to cohort_path(@cohort)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def twitter_signin
    link_to '/auth/twitter', :class => "btn btn-default" do
      raw("<i class='icon-twitter'></i>   Sign In w/ Twitter")
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  def student_name
    @student.full_name ? @student.full_name : "New Student"
  end

  def delete_link(student)
    link_to(raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'), cohort_student_path(student.cohort, student), :method => :delete)
  end

  def follow_status(student, new_friends, old_friends)
    if new_friends && new_friends.include?(student.twitter_handle)
      raw('<td class="green">Followed!</td>')
    elsif old_friends.include?(student.twitter_handle)
      raw('<td>Following</td>')
    else
      raw('<td></td>')
    end
  end
end

app/views/cohorts/_link.html.erb
<div class="cohort-container">
  <%= link_to cohort.name, cohort_path(cohort), :class => 'btn btn-info' %>
</div>

app/views/cohorts/index.html.erb
<h1 id="title">Select a Cohort!</h1>
<%= render partial: 'cohorts/link', collection: @cohorts, as: :cohort %>

app/views/cohorts/show.html.erb
<h1 id="title"><%= @cohort.name %> Roster</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th><i class="icon-twitter"></i></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @students.each do |student| %>
        <tr>
          <td></td>
          <td><%= link_to "#{student.full_name}", cohort_student_path(@cohort, student) %></td>
          <td><%= "#{student.twitter_handle}" %></td>
          <td><%= delete_link(student) %></td>
          <%= follow_status(student, flash[:new_friends], @friends) %>
        </tr>

    <% end %>
    </tbody>
  </table>


<div class="left-align">
  <%= link_to "< Back", root_path, :class => "btn btn-info" %>
  <%= link_to "Add New Student (+)", new_cohort_student_path(@cohort), :class => "btn btn-info" %>
  <%= link_to "Follow People!", cohort_twitter_follow_path(@cohort), :class => "btn btn-success" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    <a class="navbar-brand" href="#">Flatiron Connection</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
    <%- if logged_in? -%>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
    <%- else -%>
      <li><%= link_to "Sign In", signin_path %></li>
    <%- end -%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flatiron Connection</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for [@cohort, @student], :html => {:class => 'form-horizontal'} do |f| %>
  <fieldset>
    <legend><%= student_name %></legend>
      <div class="form-group">
        <%= f.label :full_name, :class => 'col-md-2' %>
        <%= f.text_field :full_name, :class => 'col-md-10', :placeholder => "Gimme yo sexy name!" %>
      </div>
      <div class="form-group">
        <%= f.label :twitter, "Twitter URL", :class => 'col-md-2' %>
        <%= f.text_field :twitter, :class => 'col-md-10', :placeholder => "Let me tweet at ya!" %>
      </div>
      <div class="form-group">
        <%= f.label :linkedin, "LinkedIn URL", :class => 'col-md-2' %>
        <%= f.text_field :linkedin, :class => 'col-md-10', :placeholder => "Can we make a connection?" %>
      </div>
      <div class="form-group">
        <%= f.label :github, "GitHub URL", :class => 'col-md-2' %>
        <%= f.text_field :github, :class => 'col-md-10', :placeholder => "Let me see yo projects!" %>
      </div>
      <div class="form-group">
        <%= f.label :quote, :class => 'col-md-2' %>
        <%= f.text_field :quote, :class => 'col-md-10', :placeholder => "Confucius say man who abuse computer get bad bytes." %>
      </div>
      <div class="form-group">
        <%= f.label :bio, :class => 'col-md-2' %>
        <%= f.text_area :bio, :class => 'col-md-10', :rows => 5, :placeholder => "You did what when?!" %>
      </div>
      <div class="form-group">
        <%= f.label :work_title, "Work Title", :class => 'col-md-2' %>
        <%= f.text_field :work_title, :class => 'col-md-10', :placeholder => "Let's be professionals here..." %>
      </div>
      <div class="form-group">
        <%= f.label :education, :class => 'col-md-2' %>
        <%= f.text_field :education, :class => 'col-md-10', :placeholder => "Oh you went to Hogwarts too?" %>
      </div>
      <div class="form-group">
        <%= f.label :profile_image, "Image URL", :class => 'col-md-2' %>
        <%= f.text_field :profile_image, :class => 'col-md-10', :placeholder => "Jeeeeah look at that smile! " %>
      </div>
      <div class="form-group">
        <span class="col-md-offset-2 col-md-10">
          <%= link_to "Cancel", cohort_path(@cohort), :class => "btn btn-default" %>
          <%= f.submit :class => 'btn btn-success' %>
        </span>
      </div>
  </fieldset>
<%- end -%>

app/views/students/edit.html.erb
<%= render 'students/form' %>

app/views/students/new.html.erb
<%= render 'students/form' %>

app/views/students/show.html.erb
<div class="page-header">
  <h1 id="title" class="text-center"><%= @student.full_name %></h1>
</div>

<div class="row">
  <div class="col-md-4 show-container">
      <div class="cover">
        <div id="twitter" class="text-center center-xy">
          <i class="icon icon-twitter"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <a href="<%= @student.twitter %>" target="_blank">
            <%= @student.twitter %>
          </a>
        </div>
      </div>
  </div>
    <div class="col-md-4 show-container">
      <div class="cover">
        <div id="github" class="text-center center-xy">
          <i class="icon icon-github-circled"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <a href="<%= @student.github %>" target="_blank">
            <%= @student.github %>
          </a>
        </div>
      </div>
  </div>
    <div class="col-md-4 show-container">
      <div class="cover">
        <div id="linkedin" class="text-center center-xy">
          <i class="icon icon-linkedin"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <a href="<%= @student.linkedin %>" target="_blank">
            <%= @student.linkedin %>
          </a>
        </div>
      </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 show-container">
      <div class="cover">
        <div id="quote" class="text-center center-xy">
          <i class="icon icon-quote"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <%= @student.quote %>
        </div>
      </div>
  </div>
  <div class="col-md-4 show-container">
      <div class="cover">
        <div id="image" class="text-center center-xy">
          <div class="show-student-img">
            <img class="show-profile-img center-xy" src="<%= @student.profile_image %>" alt="">
          </div>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <%= @student.full_name %>
        </div>
      </div>
  </div>

    <div class="col-md-4 show-container">
      <div class="cover">
        <div id="bio" class="text-center center-xy">
          <i class="icon icon-doc-text"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <%= @student.bio %>
        </div>
      </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 show-container">
        <div class="cover">
          <div id="work" class="text-center center-xy">
            <i class="icon icon-briefcase"></i>
          </div>
        </div>
        <div class="content">
          <div class="text-center center-xy">
            <%= @student.work_title %>
          </div>
        </div>
    </div>
  <div class="col-md-4 show-container">
      <div class="cover">
        <div id="education" class="text-center center-xy">
          <i class="icon icon-book-open"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <%= @student.education %>
        </div>
      </div>
  </div>
    <div class="col-md-4 show-container">

      <div class="cover">
        <div id="education" class="text-center center-xy">
          <i class="icon glyphicon glyphicon-pencil"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <%= link_to "Edit Info", edit_cohort_student_path(@cohort, @student) %>
        </div>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4 show-container">
      <div class="cover">
        <div id="education" class="text-center center-xy">
          <i class="icon glyphicon glyphicon-home"></i>
        </div>
      </div>
      <div class="content">
        <div class="text-center center-xy">
          <%= link_to "Home", cohort_path(@cohort) %>
        </div>
      </div>
  </div>
</div>